//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIdLinker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppIdLinker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;sxOD2un0IddS55rX6hg5AFtP5yYBjF54rgJn8LX4Z5A10oX/lpw44bWvrI3FKC0GbufPwjRcoVsUKCbuJuFfoKJCp0PDPRZB3qiA9dUdfpMLeC5A5kLSAG7c5NxqYJOlJfykJCgAKqmNknWqDdsjOrF9RDzfZcz3P7DWpvc3KGgLzz6gUUD67YVAQVncv7N1NZ5rUoaVDdurpOO82WrTrX2YVg1eXK7pfzD0VziOOmlubI5lhOZrm9aFscY80QGZaTbBaPQJHksfbZBSM6Uje1bun7epAs/axEst/T7rr8Ekz4lsoco53q1PeyJvL5uO8al3Dl9mHhE1yyEQ8lsqRHLN5y7CLiufjGvRLoaN0eImm87iORMbRMBTmfW83uhi4JWPUkL8RPPx9ehYJGUVFOlA8ttRvFaSPowXqTFFTuB+fwQYMhr+W/jOkgi2YbKajm3zk8ktGpNrQGjEJvkjJmejhHH8YNTJpC1K95yzbZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppIdLinkerExt_UpdateCheckFileSigKey {
            get {
                return ResourceManager.GetString("AppIdLinkerExt_UpdateCheckFileSigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Separators: &apos;|&apos; for separating domains and application IDs, and both sides can have multiple entries delimited by commas
        ///amazon.com, amazon.ca, amazon.co.uk, amazon.co.jp | com.amazon.mShop.android.shopping, com.audible.application
        ///atlassian.com | com.atlassian.android.jira.core, com.trello
        ///backblaze.com | com.backblaze.android
        ///bandcamp.com | com.bandcamp.android
        ///blizzard.com, battle.net | com.blizzard.bma
        ///desmos.com | com.desmos.calculator, com.desmos.scientific
        ///discord.com, discordapp.com, discord.gg |  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DomainAppIdDb {
            get {
                return ResourceManager.GetString("DomainAppIdDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuIcon {
            get {
                object obj = ResourceManager.GetObject("MenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
